### ISSUE TITLE
/home/csaratakij not found

### ISSUE THREAD

**Issue by jacobgc** [CSaratakij/i3wm-desktop-config#1]
> /home/jacob/.zshrc:source:6: no such file or directory: /home/csaratakij/.oh-my-zsh/oh-my-zsh.sh

When running /bin/zsh. Looks like you left in your username and not set it to the current user variable ;_;

I might make a pull request if I figure out how to fix it :)

**Comment by CSaratakij** [comment]
Oh, That's nice. Thank you :)

**Comment by jacobgc** [comment]
You're most welcome @CSaratakij. Hail DevRant

**Comment by CSaratakij** [comment]
Hail DevRant xD
